# Generated by Django 6.1.1 on 2026-09-18 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title or purpose of the meeting/event', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Additional details or agenda')),
                ('room_name', models.CharField(help_text='Name or identifier of the room', max_length=120)),
                ('start_time', models.DateTimeField(help_text='Booking start time')),
                ('end_time', models.DateTimeField(help_text='Booking end time')),
                ('attendees_count', models.PositiveIntegerField(default=1, help_text='Number of expected attendees')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Person booking the room', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['room_name', 'start_time', 'end_time'], name='bookings_bo_room_na_301322_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx')],
            },
        ),
    ]
