# Generated by Django 5.2.17 on 2026-09-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or purpose of the meeting/event', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Additional details or agenda')),
                ('room_name', models.CharField(help_text='Name or identifier of the room', max_length=120)),
                ('user_name', models.CharField(default='Organizer', help_text='Person booking the room', max_length=120)),
                ('user_email', models.EmailField(blank=True, default='', help_text='Contact email of the organizer', max_length=254)),
                ('start_time', models.DateTimeField(help_text='Booking start time')),
                ('end_time', models.DateTimeField(help_text='Booking end time')),
                ('attendees_count', models.PositiveIntegerField(default=1, help_text='Number of expected attendees')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['room_name', 'start_time', 'end_time'], name='bookings_bo_room_na_301322_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx')],
            },
        ),
    ]
