# Generated by Django 6.1.1 on 2026-09-20 06:19

from django.db import migrations
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        BtreeGistExtension(),
    ]
