# Generated by Django 6.1.1 on 2026-09-20 06:20

import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_btree_gist_extension'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'CONFIRMED')), expressions=[('room', '='), (models.Func('start_time', 'end_time', function='tstzrange'), '&&')], name='booking_prevent_overlapping'),
        ),
    ]
