# Generated by Django 6.1.1 on 2026-09-23 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_booking_prevent_overlapping'),
        ('rooms', '0003_room_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', help_text="Custom display label (e.g. '09:00 – 10:00 AM' or 'Sprint Review')", max_length=100)),
                ('start_time', models.TimeField(help_text='Start time of the slot (e.g. 09:00:00)')),
                ('end_time', models.TimeField(help_text='End time of the slot (e.g. 10:00:00)')),
                ('period', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', help_text='Time category: morning, afternoon, or evening', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this slot is available for scheduling')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display ordering sequence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, help_text='Optional room restriction. If null, slot is global across all rooms.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='rooms.room')),
            ],
            options={
                'db_table': 'time_slots',
                'ordering': ['start_time', 'sort_order'],
                'indexes': [models.Index(fields=['is_active', 'start_time'], name='timeslot_active_time_idx'), models.Index(fields=['room', 'is_active'], name='timeslot_room_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='timeslot_end_gt_start')],
            },
        ),
    ]
