# Generated by Django 6.1.1 on 2026-09-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_seed_default_timeslots'),
        ('rooms', '0003_room_hourly_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['date', 'start_time', 'sort_order']},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(blank=True, db_index=True, help_text='Optional specific calendar date. If null, slot is a daily recurring template.', null=True),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['date', 'is_active'], name='timeslot_date_active_idx'),
        ),
    ]
