# Generated by Django 6.1.1 on 2026-09-19 05:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique name or number of the meeting room', max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of occupants (must be greater than 0)', validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(help_text='Floor, wing, building, or area description', max_length=150)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenities/assets available in the room')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this room is available for scheduling')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who registered the room in the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='rooms_name_cef1ee_idx'), models.Index(fields=['is_active'], name='rooms_is_acti_b7cb02_idx'), models.Index(fields=['capacity'], name='rooms_capacit_c8100e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='room_capacity_gt_0')],
            },
        ),
    ]
