# Generated by Django 6.1.1 on 2026-09-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Room cover photo or interior layout image', null=True, upload_to='room_images/'),
        ),
    ]
