# Generated by Django 6.1.1 on 2026-09-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Hourly rental rate in INR (₹)', max_digits=10),
        ),
    ]
