# Generated by Django 6.1.1 on 2026-09-24 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='acoustics',
            field=models.CharField(blank=True, default='', help_text="Acoustics rating or specifications (e.g. 'NRC 0.88 - Soundproofed Glazing')", max_length=150),
        ),
        migrations.AddField(
            model_name='room',
            name='av_equipment',
            field=models.JSONField(blank=True, default=list, help_text='List of admin-selected Audio/Visual equipment'),
        ),
        migrations.AddField(
            model_name='room',
            name='connectivity',
            field=models.CharField(blank=True, default='', help_text="Connectivity specifications (e.g. 'Wi-Fi 6E - 1.2 Gbps Dedicated')", max_length=150),
        ),
        migrations.AddField(
            model_name='room',
            name='floor_area',
            field=models.PositiveIntegerField(blank=True, help_text='Floor area in square feet (sq ft)', null=True),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Perspective photo of the room', upload_to='room_images/')),
                ('is_primary', models.BooleanField(default=False, help_text='Indicates whether this image is the primary cover photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(help_text='Associated meeting room', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'db_table': 'room_images',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
